// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7KLEVeA-T93iccrAVvAEzFfiltZC3PcQ',
    appId: '1:339062970579:android:f5427a9428e0201b905c26',
    messagingSenderId: '339062970579',
    projectId: 'testapp-b5512',
    storageBucket: 'testapp-b5512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6vFnBg9hl5R42bC0H8yP7x19XwBvmq_Y',
    appId: '1:339062970579:ios:9f5bec15b02200fb905c26',
    messagingSenderId: '339062970579',
    projectId: 'testapp-b5512',
    storageBucket: 'testapp-b5512.appspot.com',
    iosClientId: '339062970579-2f3qpks4gtva5u9rnqfsk8jeui59utdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );
}
